services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: 
      context: ./apps/backend
    container_name: fastapi_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./apps/frontend
    container_name: react_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data:
