services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    profiles:
      - backend
      - frontend
      - full
    restart: always
    env_file:
      - envs/.env.postgres.${APP_ENV:-dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:12.4.0-alpine
    profiles:
      - backend
      - frontend
      - full
    command: migrate
    env_file:
      - envs/.env.postgres.${APP_ENV:-dev}
      - envs/.env.flyway.${APP_ENV:-dev}
    volumes:
      - ./database/migrations:/flyway/migrations
    networks:
      - db_network
    depends_on:
      postgres:
        condition: service_healthy

  mongo:
    image: mongo:8.0
    container_name: mongo_db
    profiles:
      - backend
      - frontend
      - full
      - tools
    restart: always
    env_file:
      - envs/.env.mongo.${APP_ENV:-dev}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --username $${MONGO_INITDB_ROOT_USERNAME} --password $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval \"db.adminCommand('ping')\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    profiles:
      - tools
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - envs/.env.mongo.${APP_ENV:-dev}
    networks:
      - app_network
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    build:
      context: ./apps/backend
    container_name: fastapi_backend
    profiles:
      - backend
      - frontend
      - full
    restart: always
    env_file:
      - envs/.env.postgres.${APP_ENV:-dev}
      - envs/.env.mongo.${APP_ENV:-dev}
      - envs/.env.backend.${APP_ENV:-dev}
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
      - ./data:/app/data
      - ./data/app/logs
    networks:
      - db_network
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./apps/frontend
    container_name: react_frontend
    profiles:
      - frontend
      - full
    restart: always
    env_file:
      - envs/.env.frontend.${APP_ENV:-dev}
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - ./data:/data
    networks:
      - app_network
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data:

networks:
  db_network:
  app_network:
