CREATE TABLE IF NOT EXISTS TB_PROFILE(

    PROFILE_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PROFILE_NAME VARCHAR(255) NOT NULL UNIQUE,
    PERMISSIONS JSONB NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ

);

CREATE TABLE IF NOT EXISTS TB_USER(

    USER_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    EMAIL_HASH VARCHAR(64) NOT NULL UNIQUE,
    EMAIL_ENC VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PROFILE_ID UUID NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ,
    ANONYMIZED_AT TIMESTAMPTZ DEFAULT NULL,
    FOREIGN KEY (PROFILE_ID) REFERENCES TB_PROFILE(PROFILE_UUID)

);

CREATE TABLE IF NOT EXISTS TB_SESSION(

    SESSION_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID NOT NULL,
    SOURCE_IP VARCHAR(255) NOT NULL,
    USER_AGENT VARCHAR(255) NOT NULL,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    INVALIDATED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ,
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_UUID)

);

CREATE UNIQUE INDEX IF NOT EXISTS UX_TB_SESSION_ONE_ACTIVE_PER_USER
    ON TB_SESSION (USER_ID)
    WHERE INVALIDATED_AT IS NULL;

CREATE TABLE IF NOT EXISTS TB_AUTH_ATTEMPT(

    ATTEMPT_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EMAIL_HASH VARCHAR(64) NOT NULL,
    SOURCE_IP VARCHAR(255) NOT NULL,
    SUCCESS BOOLEAN NOT NULL,
    BLOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    ATTEMPTED_AT TIMESTAMPTZ DEFAULT NOW()

);

CREATE INDEX IF NOT EXISTS IX_TB_AUTH_ATTEMPT_SOURCE_IP_ATTEMPTED_AT_DESC
    ON TB_AUTH_ATTEMPT (SOURCE_IP, ATTEMPTED_AT DESC);

CREATE TABLE IF NOT EXISTS TB_PASSWORD_RESET(

    RESET_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_UUID UUID NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    USED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (USER_UUID) REFERENCES TB_USER(USER_UUID)

);

CREATE TABLE IF NOT EXISTS TB_POLICY_VERSION(

    VERSION_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    VERSION VARCHAR(20) NOT NULL,
    POLICY_TYPE VARCHAR(255) NOT NULL CHECK (POLICY_TYPE IN ('PRIVACY_POLICY', 'TERMS_OF_USE')),
    CONTENT TEXT NOT NULL,
    EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ

);

CREATE UNIQUE INDEX IF NOT EXISTS UX_TB_POLICY_VERSION_POLICY_TYPE_VERSION
    ON TB_POLICY_VERSION (POLICY_TYPE, VERSION)
    WHERE DELETED_AT IS NULL;

CREATE TABLE IF NOT EXISTS TB_POLICY_CLAUSE(

    CLAUSE_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    POLICY_VERSION_ID UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    MANDATORY BOOLEAN NOT NULL,
    DISPLAY_ORDER INT NOT NULL,
    CREATED_AT TIMESTAMPTZ,
    UPDATED_AT TIMESTAMPTZ,
    DELETED_AT TIMESTAMPTZ,
    FOREIGN KEY (POLICY_VERSION_ID) REFERENCES TB_POLICY_VERSION(VERSION_UUID)

);

CREATE UNIQUE INDEX IF NOT EXISTS UX_TB_POLICY_CLAUSE_VERSION_CODE
    ON TB_POLICY_CLAUSE (POLICY_VERSION_ID, CODE)
    WHERE DELETED_AT IS NULL;

CREATE TABLE IF NOT EXISTS TB_CONSENT_LOG(

    LOG_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID NOT NULL,
    CLAUSE_ID UUID NOT NULL,
    POLICY_VERSION_ID UUID REFERENCES TB_POLICY_VERSION(VERSION_UUID),
    ACTION VARCHAR(255) NOT NULL CHECK (
        ACTION IN (
            'CONSENT',
            'REVOCATION',
            'CONSENT_ACCEPTED',
            'CONSENT_REVOKED'
        )
    ),
    SOURCE_IP VARCHAR(255) NOT NULL,
    USER_AGENT VARCHAR(512) NOT NULL DEFAULT 'unknown',
    CHANNEL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_UUID),
    FOREIGN KEY (CLAUSE_ID) REFERENCES TB_POLICY_CLAUSE(CLAUSE_UUID)

);

CREATE INDEX IF NOT EXISTS IX_TB_CONSENT_LOG_USER_CLAUSE_CREATED_AT_DESC
    ON TB_CONSENT_LOG (USER_ID, CLAUSE_ID, CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IX_TB_CONSENT_LOG_POLICY_VERSION_ID
    ON TB_CONSENT_LOG (POLICY_VERSION_ID);

CREATE OR REPLACE VIEW V_PENDING_CONSENT AS
SELECT
    u.USER_UUID,
    u.USERNAME,
    pv.VERSION_UUID AS POLICY_VERSION_ID,
    pv.VERSION,
    pv.POLICY_TYPE,
    c.CLAUSE_UUID,
    c.CODE AS CLAUSE_CODE,
    c.TITLE AS CLAUSE_TITLE,
    c.DESCRIPTION AS CLAUSE_DESCRIPTION,
    c.MANDATORY,
    c.DISPLAY_ORDER,
    COALESCE(last_log.ACTION, 'PENDING') AS CONSENT_STATUS
FROM TB_USER u
JOIN TB_POLICY_VERSION pv
  ON pv.DELETED_AT IS NULL
 AND pv.EFFECTIVE_FROM <= NOW()
JOIN TB_POLICY_CLAUSE c
  ON c.POLICY_VERSION_ID = pv.VERSION_UUID
 AND c.DELETED_AT IS NULL
LEFT JOIN LATERAL (
    SELECT cl.ACTION
    FROM TB_CONSENT_LOG cl
    WHERE cl.USER_ID = u.USER_UUID
      AND cl.CLAUSE_ID = c.CLAUSE_UUID
    ORDER BY cl.CREATED_AT DESC
    LIMIT 1
) last_log ON TRUE
WHERE u.DELETED_AT IS NULL
  AND u.ACTIVE = TRUE
  AND c.MANDATORY = TRUE
  AND COALESCE(last_log.ACTION, 'PENDING') NOT IN ('CONSENT', 'CONSENT_ACCEPTED');