CREATE ROLE app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_PROFILE TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_USER TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_SESSION TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_AUTH_ATTEMPT TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_PASSWORD_RESET TO app_role;
GRANT INSERT ON TABLE TB_CONSENT_LOG TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_POLICY_VERSION TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_POLICY_CLAUSE TO app_role;

CREATE ROLE log_role;
GRANT INSERT ON TABLE TB_CONSENT_LOG TO log_role;

CREATE ROLE dba_role BYPASSRLS;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dba_role;