CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_protect_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Operation not allowed: this table is append-only for LGPD compliance';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER TB_PROFILE_UPDATE_TIMESTAMP
    BEFORE UPDATE ON TB_PROFILE
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE OR REPLACE TRIGGER TB_USER_UPDATE_TIMESTAMP
    BEFORE UPDATE ON TB_USER
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE OR REPLACE TRIGGER TB_SESSION_UPDATE_TIMESTAMP
    BEFORE UPDATE ON TB_SESSION
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE OR REPLACE TRIGGER TB_POLICY_VERSION_UPDATE_TIMESTAMP
    BEFORE UPDATE ON TB_POLICY_VERSION
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE OR REPLACE TRIGGER TB_POLICY_CLAUSE_UPDATE_TIMESTAMP
    BEFORE UPDATE ON TB_POLICY_CLAUSE
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();


CREATE OR REPLACE TRIGGER TB_CONSENT_LOG_APPEND_ONLY
    BEFORE UPDATE OR DELETE ON TB_CONSENT_LOG
    FOR EACH ROW
    EXECUTE FUNCTION fn_protect_append_only();