ALTER TABLE TB_SESSION ENABLE ROW LEVEL SECURITY;
ALTER TABLE TB_CONSENT_LOG ENABLE ROW LEVEL SECURITY;
ALTER TABLE TB_USER ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;

REVOKE ALL ON TABLE TB_CONSENT_LOG FROM app_role;
REVOKE ALL ON TABLE TB_POLICY_VERSION FROM app_role;
REVOKE ALL ON TABLE TB_POLICY_CLAUSE FROM app_role;

GRANT SELECT, INSERT, UPDATE ON TABLE TB_PROFILE TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_USER TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_SESSION TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_AUTH_ATTEMPT TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_PASSWORD_RESET TO app_role;
GRANT SELECT, INSERT, UPDATE ON TABLE TB_FIRST_ACCESS_TOKEN TO app_role;

GRANT SELECT, INSERT ON TABLE TB_CONSENT_LOG TO app_role;
GRANT SELECT, INSERT ON TABLE TB_POLICY_VERSION TO app_role;
GRANT SELECT, INSERT ON TABLE TB_POLICY_CLAUSE TO app_role;

GRANT SELECT ON V_PENDING_CONSENT TO app_role;

GRANT INSERT ON TABLE TB_CONSENT_LOG TO log_role;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dba_role;

COMMENT ON COLUMN TB_USER.EMAIL_HASH IS
'Deterministic SHA-256 hash. Salt: EMAIL_HASH_SALT env var. Imutável.';

COMMENT ON COLUMN TB_AUTH_ATTEMPT.EMAIL_HASH IS
'Deterministic SHA-256 hash para correlação de auditoria.';