CREATE OR REPLACE VIEW V_PENDING_CONSENT AS
SELECT
    u.USER_UUID,
    u.USERNAME,
    pv.VERSION_UUID AS POLICY_VERSION_ID,
    pv.VERSION,
    pv.POLICY_TYPE,
    c.CLAUSE_UUID,
    c.CODE AS CLAUSE_CODE,
    c.TITLE AS CLAUSE_TITLE,
    c.DESCRIPTION AS CLAUSE_DESCRIPTION,
    c.MANDATORY,
    c.DISPLAY_ORDER,
    COALESCE(last_log.ACTION, 'PENDING') AS CONSENT_STATUS
FROM TB_USER u
JOIN TB_POLICY_VERSION pv
  ON pv.DELETED_AT IS NULL
 AND pv.EFFECTIVE_FROM <= NOW()
JOIN TB_POLICY_CLAUSE c
  ON c.POLICY_VERSION_ID = pv.VERSION_UUID
 AND c.DELETED_AT IS NULL
LEFT JOIN LATERAL (
    SELECT cl.ACTION
    FROM TB_CONSENT_LOG cl
    WHERE cl.USER_ID = u.USER_UUID
      AND cl.CLAUSE_ID = c.CLAUSE_UUID
    ORDER BY cl.CREATED_AT DESC
    LIMIT 1
) last_log ON TRUE
WHERE u.DELETED_AT IS NULL
  AND u.ACTIVE = TRUE
  AND c.MANDATORY = TRUE
  AND COALESCE(last_log.ACTION, 'PENDING') NOT IN ('CONSENT', 'CONSENT_ACCEPTED');

GRANT SELECT ON V_PENDING_CONSENT TO app_role;