ALTER TABLE TB_CONSENT_LOG
ADD COLUMN IF NOT EXISTS POLICY_VERSION_ID UUID REFERENCES TB_POLICY_VERSION(VERSION_UUID);

ALTER TABLE TB_CONSENT_LOG
ADD COLUMN IF NOT EXISTS USER_AGENT VARCHAR(512) NOT NULL DEFAULT 'unknown';

ALTER TABLE TB_CONSENT_LOG
DROP CONSTRAINT IF EXISTS tb_consent_log_action_check;

ALTER TABLE TB_CONSENT_LOG
ADD CONSTRAINT tb_consent_log_action_check
CHECK (
    ACTION IN (
        'CONSENT',
        'REVOCATION',
        'CONSENT_ACCEPTED',
        'CONSENT_REVOKED'
    )
);

CREATE INDEX IF NOT EXISTS IX_TB_CONSENT_LOG_USER_CLAUSE_CREATED_AT_DESC
ON TB_CONSENT_LOG (USER_ID, CLAUSE_ID, CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IX_TB_CONSENT_LOG_POLICY_VERSION_ID
ON TB_CONSENT_LOG (POLICY_VERSION_ID);

GRANT INSERT ON TABLE TB_CONSENT_LOG TO app_role;
GRANT SELECT ON TABLE TB_CONSENT_LOG TO app_role;