ALTER TABLE TB_SESSION
    ADD COLUMN IF NOT EXISTS REFRESH_TOKEN_HASH VARCHAR(64),
    ADD COLUMN IF NOT EXISTS REFRESH_EXPIRES_AT TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS IX_TB_SESSION_REFRESH_TOKEN_HASH
    ON TB_SESSION (REFRESH_TOKEN_HASH)
    WHERE REFRESH_TOKEN_HASH IS NOT NULL
      AND INVALIDATED_AT IS NULL
      AND DELETED_AT IS NULL;
