CREATE TABLE IF NOT EXISTS TB_PASSWORD_RESET(

    RESET_UUID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_UUID UUID NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    USED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (USER_UUID) REFERENCES TB_USER(USER_UUID)

);

CREATE UNIQUE INDEX IF NOT EXISTS UX_TB_PASSWORD_RESET_TOKEN_HASH
    ON TB_PASSWORD_RESET (TOKEN_HASH);

GRANT INSERT, SELECT, UPDATE ON TABLE TB_PASSWORD_RESET TO app_role;
GRANT ALL PRIVILEGES ON TABLE TB_PASSWORD_RESET TO dba_role;