ALTER TABLE TB_POLICY_VERSION ENABLE ROW LEVEL SECURITY;
ALTER TABLE TB_POLICY_CLAUSE ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION fn_current_user_is_admin()
RETURNS BOOLEAN AS $$
DECLARE
    v_user_id UUID;
BEGIN
    v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::UUID;

    IF v_user_id IS NULL THEN
        RETURN FALSE;
    END IF;

    RETURN EXISTS (
        SELECT 1
        FROM TB_USER u
        JOIN TB_PROFILE p
          ON p.PROFILE_UUID = u.PROFILE_ID
        WHERE u.USER_UUID = v_user_id
          AND p.PROFILE_NAME = 'ADMIN'
          AND u.ACTIVE = TRUE
          AND u.DELETED_AT IS NULL
    );
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
$$ LANGUAGE plpgsql STABLE;

DROP POLICY IF EXISTS policy_select_policy_version_public ON TB_POLICY_VERSION;
DROP POLICY IF EXISTS policy_select_policy_clause_public ON TB_POLICY_CLAUSE;
DROP POLICY IF EXISTS policy_admin_policy_version ON TB_POLICY_VERSION;
DROP POLICY IF EXISTS policy_admin_policy_clause ON TB_POLICY_CLAUSE;

CREATE POLICY policy_select_policy_version_public
ON TB_POLICY_VERSION
FOR SELECT
USING (
    DELETED_AT IS NULL
    AND EFFECTIVE_FROM <= NOW()
);

CREATE POLICY policy_select_policy_clause_public
ON TB_POLICY_CLAUSE
FOR SELECT
USING (
    DELETED_AT IS NULL
    AND EXISTS (
        SELECT 1
        FROM TB_POLICY_VERSION pv
        WHERE pv.VERSION_UUID = TB_POLICY_CLAUSE.POLICY_VERSION_ID
          AND pv.DELETED_AT IS NULL
          AND pv.EFFECTIVE_FROM <= NOW()
    )
);

CREATE POLICY policy_admin_policy_version
ON TB_POLICY_VERSION
FOR ALL
USING (fn_current_user_is_admin())
WITH CHECK (fn_current_user_is_admin());

CREATE POLICY policy_admin_policy_clause
ON TB_POLICY_CLAUSE
FOR ALL
USING (fn_current_user_is_admin())
WITH CHECK (fn_current_user_is_admin());

ALTER TABLE TB_POLICY_VERSION FORCE ROW LEVEL SECURITY;
ALTER TABLE TB_POLICY_CLAUSE FORCE ROW LEVEL SECURITY;

ALTER TABLE TB_POLICY_VERSION
DROP CONSTRAINT IF EXISTS tb_policy_version_version_key;

CREATE UNIQUE INDEX IF NOT EXISTS UX_TB_POLICY_VERSION_POLICY_TYPE_VERSION
ON TB_POLICY_VERSION (POLICY_TYPE, VERSION)
WHERE DELETED_AT IS NULL;

ALTER TABLE TB_POLICY_CLAUSE
DROP CONSTRAINT IF EXISTS tb_policy_clause_code_key;

CREATE UNIQUE INDEX IF NOT EXISTS UX_TB_POLICY_CLAUSE_VERSION_CODE
ON TB_POLICY_CLAUSE (POLICY_VERSION_ID, CODE)
WHERE DELETED_AT IS NULL;

GRANT SELECT, INSERT ON TABLE TB_POLICY_VERSION TO app_role;
GRANT SELECT, INSERT ON TABLE TB_POLICY_CLAUSE TO app_role;