-- Remove Foreign Key constraints to allow physical deletion of users
-- Historical data will be preserved with orphaned USER_ID references

ALTER TABLE IF EXISTS "TB_SESSION" DROP CONSTRAINT IF EXISTS "TB_SESSION_USER_ID_fkey";
ALTER TABLE IF EXISTS "TB_PASSWORD_RESET" DROP CONSTRAINT IF EXISTS "TB_PASSWORD_RESET_USER_ID_fkey";
ALTER TABLE IF EXISTS "TB_FIRST_ACCESS_TOKEN" DROP CONSTRAINT IF EXISTS "TB_FIRST_ACCESS_TOKEN_USER_ID_fkey";
ALTER TABLE IF EXISTS "TB_CONSENT_LOG" DROP CONSTRAINT IF EXISTS "TB_CONSENT_LOG_USER_ID_fkey";
