spring.application.name=burndown

# GitHub Configuration
github.url=https://api.github.com/graphql
github.api.url=https://api.github.com/graphql
github.api.token=${GITHUB_TOKEN:}
github.org=FatecNeoHorizon
github.project-number=3

# Logging
logging.level.com.zeus.burndown=INFO
logging.level.com.zeus.burndown.service.BurndownDataMapper=DEBUG
logging.level.org.springframework.web=WARN

spring.profiles.active=local