import base64
import hashlib

import bcrypt
from cryptography.fernet import Fernet

from src.api.schemas.user_schemas import UserCreateRequest, UserCreateResponse
from src.config.settings import Settings
from src.repositories.user_repository import create_user


def _build_email_hash(email: str, salt: str) -> str:
    payload = f"{email}:{salt}".encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _sanitize_fernet_key(raw_key: str) -> str:
    key = raw_key.strip().strip('"').strip("'")

    if key.startswith("b'") and key.endswith("'"):
        return key[2:-1]
    if key.startswith('b"') and key.endswith('"'):
        return key[2:-1]

    return key


def _resolve_email_encryption_key(settings: Settings) -> bytes:
    if settings.email_encryption_key:
        return _sanitize_fernet_key(settings.email_encryption_key).encode("utf-8")

    # Keep deterministic fallback for local/dev setups without explicit key.
    digest = hashlib.sha256(settings.email_hash_salt.encode("utf-8")).digest()
    return base64.urlsafe_b64encode(digest)


def _encrypt_email(email: str, settings: Settings) -> str:
    key = _resolve_email_encryption_key(settings)
    try:
        return Fernet(key).encrypt(email.encode("utf-8")).decode("utf-8")
    except ValueError as exc:
        raise RuntimeError(
            "EMAIL_ENCRYPTION_KEY is invalid. Use a Fernet key generated by cryptography.fernet.Fernet.generate_key()."
        ) from exc


def _hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def create_user_service(payload: UserCreateRequest) -> UserCreateResponse:
    settings = Settings()
    normalized_email = str(payload.email).strip().lower()

    result = create_user(
        username=payload.username,
        email_hash=_build_email_hash(normalized_email, settings.email_hash_salt),
        email_enc=_encrypt_email(normalized_email, settings),
        password_hash=_hash_password(payload.password),
        profile_id=payload.profile_id,
    )

    return UserCreateResponse(
        user_uuid=result.user_uuid,
        username=result.username,
        profile_id=result.profile_id,
        active=result.active,
        created_at=result.created_at,
    )
