name: Validate Commits (CommitLint)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
          helpURL: "https://www.conventionalcommits.org/"